a = "i am from bangladesh"
# print(len (a))
# print(a[18])
# print(a.title())
# print(a[4:16:2])
# print(a[-1::-1])
# print(a.upper())
# print(a.isdigit())
# # print(a.center(f,s))
# print(a.chace(e))
print(a.endswith("sh"))
print(a.find("g"))
print(a.replace("h","r"))
print(a.count("a"))